version: '2'
services:
  zoo1:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092